#!/bin/sh

# cd to the directory the shell script is stored
cd `dirname -- "$0"`

# Can be "TCP" or "MQTT"
test -z "$UPLOAD_MODE" && export UPLOAD_MODE="TCP"
#export UPLOAD_MODE="${UPLOAD_MODE:-default}"
#export "${UPLOAD_MODE:=MQTT}"

# This is the berry script we want to upload
test -z "$BERRY_FILENAME" && export BERRY_FILENAME="timetable.be"
# can be "RUN" (compile and run without writing to flash)
# or "SAVE" (compile run and save to flash filesystem)
# Most of the time you want the "RUN" command to avoid flash wear
test -z "$BERRY_COMMAND" && export BERRY_COMMAND="RUN"
# It is used on "TCP" mode. Tcpberry must be loaded
test -z "$TCP_SERVER" && export TCP_SERVER="10.5.2.170:1001"
#
test -z "$MQTT_SERVER" && export MQTT_SERVER="tls://mqtt.flespi.io:8883"
test -z "$MQTT_USERNAME" && export MQTT_USERNAME="jQW9vccrtLtBEjd9L6aiu0A3WlUxRDi44lXLBfBWkbNQst58ykfdVK1Ntyil7dMf"

test -z "$MQTT_PASSWORD" && export MQTT_PASSWORD="xyz"
# The topic is changed with "topic ..." tasmota command (or the web interface)
#export MQTT_TOPIC="gel2"
test -z "$MQTT_TOPIC" && export MQTT_TOPIC="tt"

berryupload
